### ISSUE TITLE
Unable to open spyder

### ISSUE THREAD

**Issue by Anurao33** [Anurao33/anu#1]
Anaconda is installed in my system but i'm not able to open spyder

Name: Anaconda2
# Version: 4.2.0
#Macosx

when i'm typing in command promote 'spyder', getting this error.can any one please help me with this.

Traceback (most recent call last):
  File "/Users/anusharaotaliyakula/anaconda/bin/spyder", line 4, in <module>
    import spyder.app.start
  File "/Users/anusharaotaliyakula/anaconda/lib/python3.5/site-packages/spyder/app/start.py", line 13, in <module>
    from spyder.config.base import get_conf_path, running_in_mac_app
  File "/Users/anusharaotaliyakula/anaconda/lib/python3.5/site-packages/spyder/config/base.py", line 343, in <module>
    _ = get_translation("spyder")
  File "/Users/anusharaotaliyakula/anaconda/lib/python3.5/site-packages/spyder/config/base.py", line 315, in get_translation
    language = load_lang_conf()
  File "/Users/anusharaotaliyakula/anaconda/lib/python3.5/site-packages/spyder/config/base.py", line 302, in load_lang_conf
    lang = get_interface_language()
  File "/Users/anusharaotaliyakula/anaconda/lib/python3.5/site-packages/spyder/config/base.py", line 268, in get_interface_language
    locale_language = locale.getdefaultlocale()[0]
  File "/Users/anusharaotaliyakula/anaconda/lib/python3.5/locale.py", line 558, in getdefaultlocale
    return _parse_localename(localename)
  File "/Users/anusharaotaliyakula/anaconda/lib/python3.5/locale.py", line 486, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: UTF-8

Thank you advance.

**Comment by Anurao33** [comment]
can anything solve this problem
